server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

#springdoc:
#  default-flat-param-object: true
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: cn.bugstack
#
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
# 微信公众号对接
weixin:
  config:
    originalid: gh_e1246f479693
    token: b8b6
    app-id: wx742fd4cab6a98e49
    app-secret: 705e00bd3dc1e0e81a20ba0d9a0e0795
    template_id: _ctk4C_jsl3xynkpw5eT53qFBwNgEXOnzdVJtIRwW6E

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat
# redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 16379

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000142628735
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqrV//9r6gHY3Un0w+6PEGd+xO0925n5Ie6iHg0rpxb9JqMgiRY2cXhdi5tVMKiGxloiArbRgRs4YoFT4s5oj8P3HQpwGlD2QlY8SAeRT+WpCxVdyTU+bwn2evJZpY26R7GLCqCBI1KY1AN8ypbEaU/KHfXqbsK1+IoeILSiS/LNgn3G9OaEH1WUZRdqiVzPR2C70fA3Pv4hYe1VdEva3U/269UFHJPyoHg+maujv1gG62Yc/xfGgeWqpAyoOq0Or+d/l9Wpxm32UnRxkrIHWHH1gQLjE3YjdqlZZ6Wk5uyulylpuktLid2FrrxeeHeo9jwcCBulHtpNvOCc4WwvBHAgMBAAECggEARTl+p12XoW97OBLIJPfr0jjPooUx9/itllZWGU6/CgVVrXbPnNBZXuQNq/zMSohclrg0Hgjoaz2KGzXKewGh69V7vyoNc7oTX0rgx07U4fkvmI1/ok20bEHrFtHEkWe8haTU+pG9eMx6muJG4yykUAdLTEKip0VMQSmPeg6/ar4EBmGSVtwJjAtcXJHzhV6MT7nvO+nIMcMzQVP3v8qZQfwkLMbXsVb8rZq29Lv8v9lbVsYq5GoR9hlCuJzPArlzFgR1CtT+xpWv/dHzhI3WGMTXpArCMUXL8wknlxfMrzeDCjlwvav/bhm3y2Xm3d5DYYbLh5+9eryYErkFBJ59WQKBgQD71nu4QQ4iFjLbywXAb8QDB/nzwvdV+VtNQawTlWx2F5BTJVVeg0Z8ymR/aUiNYbn8U4pkvIMd3/qnDele/G5bVee2IvSaF4snbKTWEBDV14AFPGTT/bIinqrph0Ok3JABL7cJ9CVglYjEZWgZABNa5tt4ONd4g1vWEVuD+kih3QKBgQCtf4EWWxRpbpga/lfdkhpgzyMpQZw5R92ZBZ5dwhMxqreeGnNQMN0LncPxw3gLF/frTSDjBRRZbhWnW/0k4NjA/kYOXttz1XRnJZYCIWn+hpNs5jxRGYVFArmyPAx8EJr7qRT0J8O8NmmractbK/c7u31EHEhbvv+PNzRplrCCcwKBgDof2NJAAZkQcpCUHTG7GgxxDNmcCCYJtW7xV1v1wuDGs4LdPQThW6V1uRhHHn2zLo/0YB67+68rgNiJt3E65eWiwCYjjzz5bh6dTrYxYxFX+a47sDHVfgXLhTr9AznLxljfwGlFtlLCcJyToyESCWWTntfylpi0CMAxpWOiopzpAoGAJM2dRm6/n7XUEjXN0bSCX/LQlJnUV9pEyYcFlwHqLGj4VlNqDqKu4R3wSMKcHk5RStqrlTyommfdtAixZDdGA3psxfOdPa8T6CVy8rS/1Twa3cjhFpsBSChR19shEtg66BNv3HLq9GvecnwYpRhoc4VMBzywpLWZZHnjZlqOyr0CgYEAzf3A1VwkOPxYzF0eC6HeLERm9DoMw7/2kidbHMkUuWZt1ZnWiAxSqFgaZ8wZF3JLSg+BmYK3jgS4AINVVB1PW0A2e2ct7rviYWVH37+d7mSe228sZHZo+7TYczctlvu3t3xT+PLIqnmgiCqLsFNMfhxNDZ2wQgwvFyaXnAb0vhY=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr5ryP9CvPjVmUoHDOGuKvHlNFNRp6yQAV7+DXAsjrnCwAM8Hj/5Bv1MBJT7SXJwqgZyArErp1kDD9cOFpTKJWQnw/CIoiBbqNAbtjWAQ5gSns8wN1Wpfq73y8GTW7l5C5fbfDmHM83fhXUgZABsDeguujO2bOvVJSoyRSmWPw2lEq8OxiCt1L8p3n2sbi8wfCPWP4jy0NLmHg7y+nkSmvyTMF8Oi7nRYASsz4/W2YuiJCdDok3HggBbGPgJSjuw4F43i+VWPofK1ezyIvOeAAputRy+ffzR4k/NjTLRylWb9Gh0d/mbkaMdEvF8ULyg0CXr5jtv7cFrlGCG8WKoURwIDAQAB
  notify_url: http://yanami.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml